# Preprocessing

## Labels

In [3]:
import pandas as pd
import numpy as np
import os

names = ['권구민', '김나현', '김준아', '박소정', '송채연', '염예찬', '이종진', '정소영', '조은상', '최무성', '황상빈', '황시훈']
quiz_num = ['quiz_1', 'quiz_2', 'quiz_3', 'quiz_4', 'quiz_5', 'quiz_6']

# labels 먼저 선언
answer = pd.read_excel("data/result.xlsx")
correct = answer[2 : 14]
correct = correct.drop(columns=["Unnamed: 0", "Unnamed: 7", "Unnamed: 8"])
correct.index = names
correct.columns = quiz_num
labels = correct

# Pass_Quiz
Pass_Quiz = answer[19 : 31]
Pass_Quiz = Pass_Quiz.drop(columns=["Unnamed: 0", "Unnamed: 7", "Unnamed: 8"])
Pass_Quiz.index = names
Pass_Quiz.columns = quiz_num

## First Reading Data

In [7]:
def get_all_csv_files(root_folder):
    csv_files = []
    for root, _, files in os.walk(root_folder):
        for file in files:
            if(file.endswith('.csv')):
                csv_files.append(os.path.join(root, file))
    return csv_files

def read_concat_csv(csv_files):
    dataframes = []
    for file in csv_files:
        df = pd.read_csv(file)
        folder_name = os.path.basename(os.path.dirname(file))
        df['folder_name'] = folder_name
        dataframes.append(df)
    concat_df = pd.concat(dataframes, ignore_index = True)
    return concat_df

root_folder = 'data/first_reading'
csv_files = get_all_csv_files(root_folder)

first_df = read_concat_csv(csv_files) # first_df -> first_reading_df : 처음 지문을 읽은 시선 좌표들

first_df

                  x            y folder_name  time
0        905.875488  2988.187256    박소정   NaN
1        872.334839  3013.673828    박소정   NaN
2        852.195374  3030.489502    박소정   NaN
3        851.903687  3029.890625    박소정   NaN
4        850.856873  3026.110352    박소정   NaN
...             ...          ...         ...   ...
169434  1591.697388  1665.480713    황시훈   NaN
169435  1595.373413  1650.665649    황시훈   NaN
169436  1594.761841  1643.754883    황시훈   NaN
169437  1587.083618  1623.411499    황시훈   NaN
169438  1685.490479  1596.803955    황시훈   NaN

[169439 rows x 4 columns]