In [24]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 2.7 MB/s eta 0:00:00a 0:00:01
Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [76]:
import pandas as pd
import numpy as np

names = ['권구민', '김나현', '김준아', '박소정', '송채연', '염예찬', '이종진', '정소영', '조은상', '최무성', '황상빈', '황시훈']

# labels 먼저 선언
answer = pd.read_excel("data/result.xlsx")
correct = answer[2 : 14]
correct = correct.drop(columns=["Unnamed: 0", "Unnamed: 8"])
correct.index = names
labels = correct

# Pass_Quiz
Pass_Quiz = answer[19 : 31]
Pass_Quiz = Pass_Quiz.drop(columns=["Unnamed: 0", "Unnamed: 7", "Unnamed: 8"])
Pass_Quiz.index = names
Pass_Quiz

    Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6
권구민         15         10          8         11         15         17
김나현         10         15          8          7          8          8
김준아         17         10          7         12         15          9
박소정         12         20         11          7         19         16
송채연         18         11          5          5         14         21
염예찬         19         16          8         11         17         12
이종진         14         11          2          4         13          5
정소영         21         13         14         20         24         23
조은상          9          8          7          6         11         13
최무성          5         11          4          6         15          5
황상빈          5          6          1          8         18         10
황시훈         26         26         16         27         32         31